name: widget_extensions
description: An Extension library for Flutter Widgets.
version: 0.0.2
authors: [Pramukesh <n.bhargavvenky@gmail.com>, CANewsIn(Organisation) <canews.in@gmail.com>]
homepage: https://github.com/canewsin/widget_extensions
repository: https://github.com/canewsin/widget_extensions
issue_tracker: https://github.com/canewsin/widget_extensions\issues

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.15-pre.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
